Add Home page, About Page and Javascript files for dynamically outputing speakers and toggle menu
Efiamotu-1/Capstone-Project pull request #1
Opened 2022-07-28 12:10 UTC by Efiamotu-1

## Features Added

>- Dynamic home page for both mobile and desktop devices
>- html, css and javascript linter files
>- About page to show more deails about the website
>- Menu.js file to handle menu toggle and navigating to differerent pages
>- Speakers.js files takes each speaker as an array of objects and outputs them dynamically to the home page
>- images, logo, color, and fonts for both home and about page

2022-07-28 12:30 UTC, youmari requested changes
Hi @Efiamotu-1 , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
✅ Clean design 
✅ Pro PR
✅ No linter error 


## Suggested changes

- [ ] Please Kindly make sure to add the presentation video as stated in the requirements 
Project documentation
Once you have finished the development of the project, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

A description of the project.
A demo of the project features (different pages and different screen sizes).
You should also highlight some interesting piece of code or something you built that you are very proud of.

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-28 12:30 UTC, youmari commented on README.md
> +[Live Demo Link]()
- [ ] It would be better to deploy the website with GitHub pages and add the link here

2022-07-28 12:30 UTC, youmari commented on js/speakers.js
> +// const seeMore = document.getElementById('see-more-speakers');
- [ ] Please it would be better to remove the unused commented code in order to keep you file clean and pro

2022-07-28 12:30 UTC, youmari commented on index.html
> +                <h1>Main Program</h1>
- [ ] Please it would be better to only one `<h1>`tag for better HTML structure and also won't confuse the google bot

2022-07-28 12:30 UTC, youmari commented on index.html
> +                    <img src="images/lecture.png" alt="">
- [ ] it would be better to not leave the `alt` attribute empty that will help people that can't see to know what is the image for

2022-07-28 12:30 UTC, youmari commented on about.html
> +    </footer>
- [ ] The footer in the desktop version should have dark background please try to do that

2022-07-28 12:30 UTC, youmari commented on index.html
> +                    <li><a href="#" class="nav-links">Home</a></li>
- [ ] Please make sure that Home link in the navigation takes you to `index.html` right now it's not working

2022-07-28 12:30 UTC, youmari commented on index.html
> +            </nav>
- [ ] Please make sure that the `Navbar` in mobile version has the same color as the headline section, I encourage you to do that 
<img width="446" alt="Screen Shot 2022-07-28 at 13 26 42" src="https://user-images.githubusercontent.com/61790587/181504849-5a4f70fd-4196-4e77-a052-3e23a1d68458.png">

2022-07-29 13:49 UTC, Nemwel-Boniface approved these changes
## Hello @Efiamotu-1               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making all the changes requested by the previous reviewer good job! :partying_face:  You have an awesome project :fire: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

- [ ] [OPTIONAL] - Kindly check your live version the images of the speakers are not showing.

![image](https://user-images.githubusercontent.com/86318284/181769253-672aee7d-5323-4bc4-90e2-995eced74f9b.png)



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 13:51 UTC, merged

2022-11-06 18:27 UTC, Efiamotu-1 commented
@Nemwel-Boniface Thanks for approving the review